### ISSUE TITLE
Weka packages: alternative path

### ISSUE THREAD

**Issue by fracpete** [fracpete/python-weka-wrapper#34]
WinPython is a self contained Python distribution, which changes the home directory of the user. Instead of only accepting `True` or `False` for the `packages` parameter when starting up the JVM, an alternative path should get accepted as well.

**Comment by fracpete** [comment]
The `packages` parameter of the `weka.core.jvm.start()` function can be used for specifying an alternative Weka home directory now as well.

**Comment by erexhepa** [comment]
Hi,

I'm having some troubles with javabridge when trying to specify an alternative path for weka packages downloaded via the package manager. So, these packages are all stored in the HOME/wekafiles directory but if I start jvm with the following code:

import weka.core.jvm as jvm
import weka.core.packages as packages
jvm.start(packages = "/home/osboxes/wekafiles/packages")

I get the following error message : 

-----------------------------------------------------------------------------------------------------------

DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Adding Weka packages, using: /home/osboxes/wekafiles
DEBUG:weka.core.jvm:package_dir=/home/osboxes/wekafiles/packages
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/EAR4
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/AffectiveTweets
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/DTNB
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/J48graft
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/DilcaDistance
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/Auto-WEKA
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/CHIRP
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/MultiObjectiveEvolutionarySearch
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/MultiObjectiveEvolutionaryFuzzyClassifier
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/NNge
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/AnDE
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/IWSSembeddedNB
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/IBkLG
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/JCDT
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/EMImputation
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/MODLEM
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/ArabicStemmers_LightStemmers
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/LibLINEAR
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/IWSS
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/GPAttributeGeneration
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/MTreeClusterer
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/LibSVM
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/CVAttributeEval
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/HMM
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/AnalogicalModeling
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/LVQ
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/DistributionBasedBalance
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/JDBCDriversDummyPackage
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/CAAR
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/EvolutionarySearch
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/IPCP
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/J48Consolidated
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/CLOPE
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/EBMC
DEBUG:weka.core.jvm:  directory=/home/osboxes/wekafiles/packages/DMNBtext
DEBUG:weka.core.jvm:Classpath=['/usr/local/lib/python2.7/dist-packages/javabridge/jars/rhino-1.7R4.jar', '/usr/local/lib/python2.7/dist-packages/javabridge/jars/runnablequeue.jar', '/usr/local/lib/python2.7/dist-packages/javabridge/jars/cpython.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/python-weka-wrapper.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/python-weka-wrapper.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/python-weka-wrapper.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/python-weka-wrapper.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/python-weka-wrapper.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/python-weka-wrapper.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/weka.jar', '/usr/local/lib/python2.7/dist-packages/weka/lib/python-weka-wrapper.jar', '/home/osboxes/wekafiles/packages/AffectiveTweets/AffectiveTweets.jar', '/home/osboxes/wekafiles/packages/AffectiveTweets/lib/fastutil-7.0.13.jar', '/home/osboxes/wekafiles/packages/AffectiveTweets/lib/SentiStrength.jar', '/home/osboxes/wekafiles/packages/AffectiveTweets/lib/ark-tweet-nlp-0.3.2.jar', '/home/osboxes/wekafiles/packages/DTNB/DTNB.jar', '/home/osboxes/wekafiles/packages/J48graft/J48graft.jar', '/home/osboxes/wekafiles/packages/DilcaDistance/DilcaDistance.jar', '/home/osboxes/wekafiles/packages/Auto-WEKA/autoweka.jar', '/home/osboxes/wekafiles/packages/CHIRP/CHIRP.jar', '/home/osboxes/wekafiles/packages/MultiObjectiveEvolutionarySearch/MultiObjectiveEvolutionarySearch.jar', '/home/osboxes/wekafiles/packages/MultiObjectiveEvolutionaryFuzzyClassifier/MultiObjectiveEvolutionaryFuzzyClassifier.jar', '/home/osboxes/wekafiles/packages/NNge/NNge.jar', '/home/osboxes/wekafiles/packages/AnDE/AnDE.jar', '/home/osboxes/wekafiles/packages/IWSSembeddedNB/IWSSembeddedNB1.0.0.jar', '/home/osboxes/wekafiles/packages/IBkLG/IBkLG.jar', '/home/osboxes/wekafiles/packages/JCDT/JCDT.jar', '/home/osboxes/wekafiles/packages/EMImputation/EMImputation.jar', '/home/osboxes/wekafiles/packages/MODLEM/modlem.jar', '/home/osboxes/wekafiles/packages/ArabicStemmers_LightStemmers/lib/lucene-core-3.0.1.jar', '/home/osboxes/wekafiles/packages/ArabicStemmers_LightStemmers/lib/lucene-analyzers-3.0.1.jar', '/home/osboxes/wekafiles/packages/ArabicStemmers_LightStemmers/ArabicStemmers_LightStemmers.jar', '/home/osboxes/wekafiles/packages/LibLINEAR/LibLINEAR.jar', '/home/osboxes/wekafiles/packages/LibLINEAR/lib/liblinear-java-1.96-SNAPSHOT.jar', '/home/osboxes/wekafiles/packages/IWSS/IWSS.jar', '/home/osboxes/wekafiles/packages/GPAttributeGeneration/GPAttributeGeneration.jar', '/home/osboxes/wekafiles/packages/MTreeClusterer/MTree.jar', '/home/osboxes/wekafiles/packages/LibSVM/LibSVM.jar', '/home/osboxes/wekafiles/packages/LibSVM/lib/libsvm.jar', '/home/osboxes/wekafiles/packages/CVAttributeEval/CVAttributeEval.jar', '/home/osboxes/wekafiles/packages/HMM/HMM.jar', '/home/osboxes/wekafiles/packages/AnalogicalModeling/Weka_AnalogicalModeling-0.03.jar', '/home/osboxes/wekafiles/packages/LVQ/LVQ.jar', '/home/osboxes/wekafiles/packages/DistributionBasedBalance/DistributionBasedBalance.jar', '/home/osboxes/wekafiles/packages/EvolutionarySearch/EvolutionarySearch.jar', '/home/osboxes/wekafiles/packages/IPCP/IPCP.jar', '/home/osboxes/wekafiles/packages/J48Consolidated/J48Consolidated.jar', '/home/osboxes/wekafiles/packages/CLOPE/CLOPE.jar', '/home/osboxes/wekafiles/packages/EBMC/ebmc.jar', '/home/osboxes/wekafiles/packages/DMNBtext/DMNBtext.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:javabridge.jutil:Creating JVM object
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 279, in start_thread
    env = vm.create(args)
  File "_javabridge.pyx", line 615, in _javabridge.JB_VM.create (_javabridge.c:6647)
RuntimeError: Failed to create Java VM. Return code = -5
ERROR:javabridge.jutil:Failed to create Java VM
DEBUG:javabridge.jutil:Signalling caller

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-b1cd2d365662> in <module>()
      2 import weka.core.packages as packages
      3 
----> 4 jvm.start(packages = "/home/osboxes/wekafiles")

/usr/local/lib/python2.7/dist-packages/weka/core/jvm.pyc in start(class_path, bundled, packages, system_cp, max_heap_size)
    130     logger.debug("MaxHeapSize=" + ("default" if (max_heap_size is None) else max_heap_size))
    131 
--> 132     javabridge.start_vm(run_headless=True, max_heap_size=max_heap_size)
    133     javabridge.attach()
    134     started = True

/usr/local/lib/python2.7/dist-packages/javabridge/jutil.pyc in start_vm(args, class_path, max_heap_size, run_headless)
    310     start_event.wait()
    311     if not _javabridge.get_vm().is_active():
--> 312         raise RuntimeError("Failed to start Java VM")
    313     attach()
    314 

RuntimeError: Failed to start Java VM

----------------------------------------------------------------------------------------------------

has anyone come accross this error and has found a solution ?

Thanks
Elton

**Comment by fracpete** [comment]
I just ran the following code:
```python
import weka.core.jvm as jvm
from weka.classifiers import Classifier

jvm.start(packages="/home/fracpete/wekafiles.alt")
cls = Classifier(classname="weka.classifiers.trees.J48")
print(cls.to_commandline())
jvm.stop()
```
Which generated the following output:
```
/usr/bin/python2.7 /home/fracpete/development/projects/python-weka-wrapper/python/weka/blah.py
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Adding Weka packages, using: /home/fracpete/wekafiles.alt
DEBUG:weka.core.jvm:package_dir=/home/fracpete/wekafiles.alt/packages
DEBUG:weka.core.jvm:  directory=/home/fracpete/wekafiles.alt/packages/gridSearch
DEBUG:weka.core.jvm:  directory=/home/fracpete/wekafiles.alt/packages/multisearch
DEBUG:weka.core.jvm:  directory=/home/fracpete/wekafiles.alt/packages/graphviz-treevisualize
DEBUG:weka.core.jvm:Classpath=['/usr/local/lib/python2.7/dist-packages/javabridge/jars/rhino-1.7R4.jar', '/usr/local/lib/python2.7/dist-packages/javabridge/jars/runnablequeue.jar', '/usr/local/lib/python2.7/dist-packages/javabridge/jars/cpython.jar', '/home/fracpete/development/projects/python-weka-wrapper/python/weka/lib/python-weka-wrapper.jar', '/home/fracpete/development/projects/python-weka-wrapper/python/weka/lib/weka.jar', '/home/fracpete/wekafiles.alt/packages/gridSearch/gridSearch.jar', '/home/fracpete/wekafiles.alt/packages/multisearch/multisearch-2016.6.7.jar', '/home/fracpete/wekafiles.alt/packages/graphviz-treevisualize/graphviz-treevisualize-2017.3.3.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:javabridge.jutil:Creating JVM object
Picked up JAVA_TOOL_OPTIONS: -Djsse.enableSNIExtension=false -XX:-OmitStackTraceInFastThrow -Dsun.java2d.xrender=false
DEBUG:javabridge.jutil:Signalling caller
weka.classifiers.trees.J48 -C 0.25 -M 2
```
Since you do have a lot of packages installed, maybe one of them is causing the problem?
What java version are you using (`java -version`)? Maybe one of the packages requires a later version?

**Comment by erexhepa** [comment]
Hi ,

Thanks for the reply. I'm on jdk1.8.0 but you're right it could be one of the packages that is causing the JVM to fail on starting. I will try to add them one by one and see which one is causing problems. Do you know if there is a jvm compatibility table for the weka packages available online somewhere ?

**Comment by fracpete** [comment]
Java 8 should be fine. Weka only requires Java 7, but some (external) packages have been built with 8. There is no JVM compatibility table availabel AFAIK.

**Comment by erexhepa** [comment]
thanks!

**Comment by fracpete** [comment]
Just to make sure: don't use OpenJDK, but an Oracle JDK.

**Comment by addyag93** [comment]
Unable to use python-wrapper-weka3 package 
Getting this error

jvm.start(system_cp=True, packages='/Users/addy93/wekafiles/packages')
DEBUG:weka.core.jvm:Adding bundled jars
DEBUG:weka.core.jvm:Adding system classpath
DEBUG:weka.core.jvm:Classpath=['/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/rhino-1.7R4.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/runnablequeue.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jars/cpython.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Applications/weka-3-8-0/weka.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar', '/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/lib/python-weka-wrapper.jar']
DEBUG:weka.core.jvm:MaxHeapSize=default
DEBUG:weka.core.jvm:Using alternative Weka home directory: /Users/addy93/wekafiles/packages
Failed to get class Lweka/core/Environment;
Exception in thread "Thread-21" java.lang.NoClassDefFoundError: Lweka/core/Environment;
Caused by: java.lang.ClassNotFoundException: weka.core.Environment
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/core/jvm.py", line 114, in start
    env = Environment.system_wide()
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/weka/core/classes.py", line 729, in system_wide
    "Lweka/core/Environment;", "getSystemWide", "()Lweka/core/Environment;"))
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jutil.py", line 934, in static_call
    fn = make_static_call(class_name, method_name, sig)
  File "/Users/addy93/PycharmProjects/Test/venv/lib/python3.6/site-packages/javabridge/jutil.py", line 908, in make_static_call
    raise JavaException(jexception)
javabridge.jutil.JavaException: Lweka/core/Environment;
